/**
 * @file src/main/agent-injection.ts
 * @purpose The injection ADAPTER layer (misc/探讨：上下文注入和联动机制):
 *   the protocol stays "shell only sets FOCUS_DOC"; this module manages the
 *   machine-level focus-context script (~/.iris/focus-context.ps1) and the
 *   detect/suggest/write-after-confirmation flow for the agent CLIs whose
 *   SessionStart hooks can call it.
 *
 * Hook configs live in the USER'S agent config files (~/.claude/settings.json
 * etc.) — not Iris's. Writing them is therefore gated behind an explicit
 * user confirmation in the settings UI. Same posture as the AGENTS.md
 * guidance append (the single sanctioned boundary exception).
 *
 * Windows-first: the script is PowerShell and the hook command invokes
 * powershell.exe. POSIX variants are a later milestone.
 */
import { promises as fs } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import type { ContextPreview, HookCliInfo, HookCliState, InjectionState } from '@shared/types';
import { irisHomeDir } from './settings-manager';
import {
  buildSoftwareBlock,
  parseProjectBlock,
  parseSoftwareBlock,
  removeSoftwareBlock,
  upsertProjectBlock,
  upsertSoftwareBlock,
  type UpsertAction,
} from './software-prompt';
import { logger } from './logger';
import { mainT } from './i18n';

/** ~/.iris/focus-context.ps1 — always the REAL ~/.iris (hooks written into
 *  agent configs must keep working whether Iris runs as dev or packaged). */
export function focusScriptPath(): string {
  return join(irisHomeDir(), 'focus-context.ps1');
}

/**
 * The script itself (prompt-governance 动态腿, §3B): document sessions carry
 * FOCUS_DOC and workspace hubs carry IRIS_WORKSPACE_PATH. Both inline the
 * dynamic context layers; document
 * sessions additionally include the focused doc, while hubs emit workspace
 * metadata only. Static software/project prompts already come from the entry
 * file; the hook adds only workspace/focus context. The focus doc degrades to a pointer above 32 KiB. A random
 * terminal with neither Iris variable prints nothing.
 *
 * Written with a UTF-8 BOM so Windows PowerShell 5.1 parses the non-ASCII text
 * (without a BOM it reads the file as the system ANSI codepage — GBK on a
 * Chinese Windows — and mangles every multibyte char). The OutputEncoding line
 * forces stdout to UTF-8 so the injected context is not mojibake either. PS
 * strings are single-quoted / concatenated to avoid backtick escapes colliding
 * with this JS template literal.
 */
export const FOCUS_CONTEXT_SCRIPT = `# Iris focus-context (machine layer, generated by Iris — editing is fine)
# SessionStart-hook payload: reads FOCUS_DOC or IRIS_WORKSPACE_PATH (set by
# Iris when spawning a terminal) and inlines dynamic context.
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$focus = $env:FOCUS_DOC
$workspace = $env:IRIS_WORKSPACE_PATH
if (-not $focus -and -not $workspace) { exit 0 }
$root = (Get-Location).Path

# Keep the first character non-JSON: Codex otherwise treats a leading '[' as
# a JSON array and reports "invalid session start JSON" instead of using text.
if ($focus) {
  Write-Output ('Iris: This terminal was started by Iris; project root: ' + $root + '; focused document: ' + $focus)
} else {
  Write-Output ('Iris: This terminal was started by Iris; project root: ' + $root + '; workspace: ' + $workspace)
  Write-Output ('<iris-workspace path="' + $workspace + '">')
  if ($workspace -eq '.iris') {
    Write-Output 'This is a project-root hub session. It was opened from the project root and is not focused on any document. FOCUS_DOC is unset, and no actual <iris-focus> block is injected. Do not read or infer a focused document; wait for the user''s instruction.'
  } else {
    Write-Output ('This is a workspace hub session opened from ' + $workspace + '. It is not focused on any document. FOCUS_DOC is unset, and no actual <iris-focus> block is injected. Do not read or infer a focused document; wait for the user''s instruction.')
  }
  Write-Output '</iris-workspace>'
}
Write-Output 'The injected layers follow. Environment variables and reading files from disk are fallbacks only: do not re-read content already injected unless you have reason to believe it changed. The content below is a snapshot taken at session start.'

# focused document — snapshot, degrade to a pointer above 32 KiB. Hub
# sessions intentionally omit the entire iris-focus block.
if ($focus) {
  $doc = Join-Path $root $focus
  Write-Output ('<iris-focus path="' + $focus + '">')
  if (Test-Path -LiteralPath $doc) {
    $size = (Get-Item -LiteralPath $doc).Length
    if ($size -le 32768) {
      Get-Content -Raw -LiteralPath $doc -Encoding UTF8
    } else {
      Write-Output ('The focused document exceeds 32 KiB (' + $size + ' bytes), so its contents were not inlined. Read the file directly.')
    }
  } else {
    Write-Output 'The focused document is not currently on disk and may have been moved or deleted. Keep the path as context and wait for the user''s instruction.'
  }
  Write-Output '</iris-focus>'
}
`;

/** The one command every JSON-hook CLI gets pointed at. */
export function hookCommand(): string {
  return `powershell -NoProfile -ExecutionPolicy Bypass -File "${focusScriptPath()}"`;
}

// ──────────────────────────────────────────────────────────────────
// CLI descriptors
// ──────────────────────────────────────────────────────────────────

interface ContextHookAdapter {
  id: string;
  label: string;
  dir: string; // config dir under home — its presence is the install signal
  file: string; // settings file inside that dir
  /** Key inside hooks{} — Claude-compatible everywhere except Cursor's casing. */
  hookKey: string;
}

/** App-owned context adapters, independent from the user launcher list. */
function contextHookAdapters(): ContextHookAdapter[] {
  const home = homedir();
  return [
    { id: 'claude', label: 'Claude Code', dir: join(home, '.claude'), file: 'settings.json', hookKey: 'SessionStart' },
    { id: 'gemini', label: 'Gemini CLI', dir: join(home, '.gemini'), file: 'settings.json', hookKey: 'SessionStart' },
    { id: 'qwen', label: 'Qwen Code', dir: join(home, '.qwen'), file: 'settings.json', hookKey: 'SessionStart' },
    { id: 'cursor', label: 'Cursor CLI', dir: join(home, '.cursor'), file: 'cli.json', hookKey: 'sessionStart' },
    // Codex supports the same hook schema in a user-level hooks.json. Keeping
    // it separate from config.toml avoids rewriting hand-maintained settings.
    { id: 'codex', label: 'Codex CLI', dir: join(home, '.codex'), file: 'hooks.json', hookKey: 'SessionStart' },
  ];
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

/** A handler counts as ours iff its command mentions Iris's generated script. */
function isIrisHandler(value: unknown): value is Record<string, unknown> {
  if (!value || typeof value !== 'object') return false;
  const command = (value as Record<string, unknown>)['command'];
  return typeof command === 'string' && command.includes('focus-context.ps1');
}

function eventHandlers(config: Record<string, unknown>, hookKey: string): unknown[] {
  const hooks = config['hooks'];
  if (!hooks || typeof hooks !== 'object') return [];
  const groups = (hooks as Record<string, unknown>)[hookKey];
  if (!Array.isArray(groups)) return [];
  return groups.flatMap((group) => {
    if (!group || typeof group !== 'object') return [];
    const handlers = (group as Record<string, unknown>)['hooks'];
    return Array.isArray(handlers) ? handlers : [];
  });
}

export async function injectionState(): Promise<InjectionState> {
  const clis: HookCliInfo[] = [];

  for (const cli of contextHookAdapters()) {
    const configPath = join(cli.dir, cli.file);
    if (!(await exists(cli.dir))) {
      clis.push({ id: cli.id, label: cli.label, configPath, state: 'cli-not-found' });
      continue;
    }
    let state: HookCliState = 'not-configured';
    try {
      const text = await fs.readFile(configPath, 'utf8');
      const config = JSON.parse(text) as Record<string, unknown>;
      const ours = eventHandlers(config, cli.hookKey).filter(isIrisHandler);
      if (ours.length > 0) {
        state = ours.every(
          (handler) => handler['type'] === 'command' && handler['command'] === hookCommand(),
        )
          ? 'configured'
          : 'stale';
      }
    } catch {
      /* missing or unparsable settings file → treat as not configured */
    }
    clis.push({ id: cli.id, label: cli.label, configPath, state });
  }

  const codex = clis.find((cli) => cli.id === 'codex');
  if (codex) {
    codex.detail = mainT('settings.codexHookDetail');
  }

  return {
    script: {
      path: focusScriptPath(),
      state: await focusScriptState(),
      hookCommand: hookCommand(),
    },
    clis,
  };
}

/** Write (or refresh) the machine-level script. App-owned — overwrite OK.
 *  Written with a UTF-8 BOM (\\uFEFF): Windows PowerShell 5.1 only detects
 *  UTF-8 via the BOM, else it reads the file as the system ANSI codepage and
 *  the Chinese text / em-dashes break the parse (the SessionStart hook error
 *  reported at focus-context.ps1:17). */
const UTF8_BOM = String.fromCharCode(0xfeff); // U+FEFF — see installFocusScript

async function focusScriptState(
  path = focusScriptPath(),
): Promise<'missing' | 'stale' | 'current'> {
  try {
    const text = await fs.readFile(path, 'utf8');
    return text === UTF8_BOM + FOCUS_CONTEXT_SCRIPT ? 'current' : 'stale';
  } catch {
    return 'missing';
  }
}

async function writeFocusScript(path: string): Promise<void> {
  await fs.mkdir(dirname(path), { recursive: true });
  await fs.writeFile(path, UTF8_BOM + FOCUS_CONTEXT_SCRIPT, 'utf8');
  logger.info('agent', `focus-context script written: ${path}`);
}

/**
 * Keep Iris's machine script current without user intervention. Hook configs
 * are user-owned and remain confirmation-gated; this generated file is
 * app-owned and every installed version points to the same stable path, so
 * allowing a stale copy to run only creates a split-brain runtime.
 */
export async function ensureFocusScriptCurrent(
  path = focusScriptPath(),
): Promise<{ path: string; action: 'created' | 'updated' | 'unchanged' }> {
  const state = await focusScriptState(path);
  if (state === 'current') return { path, action: 'unchanged' };
  await writeFocusScript(path);
  return { path, action: state === 'missing' ? 'created' : 'updated' };
}

/** Explicit recovery endpoint retained for IPC/backward compatibility. */
export async function installFocusScript(): Promise<{ path: string }> {
  const path = focusScriptPath();
  await writeFocusScript(path);
  return { path };
}

// ──────────────────────────────────────────────────────────────────
// Static leg — the `<iris-software>` managed block in entry files (§3A).
// ──────────────────────────────────────────────────────────────────

export interface EntrySyncResult {
  /** Whether the file existed before this write. */
  existed: boolean;
  action: Exclude<UpsertAction, 'removed'>;
}

/**
 * Insert or refresh the `<iris-software>` block in one entry file, preserving
 * everything outside it. Writes only when the block actually changes (no
 * needless file-watcher echo). Does NOT create the file's parent unless we're
 * actually writing.
 */
export async function syncEntryFile(absPath: string): Promise<EntrySyncResult> {
  let existed = true;
  let current = '';
  try {
    current = await fs.readFile(absPath, 'utf8');
  } catch {
    existed = false;
  }
  const { text, action } = upsertSoftwareBlock(current);
  if (action !== 'unchanged') {
    await fs.mkdir(dirname(absPath), { recursive: true });
    await fs.writeFile(absPath, text, 'utf8');
    logger.info('agent', `software block ${action} in ${absPath}`);
  }
  return { existed, action };
}

// ──────────────────────────────────────────────────────────────────
// Read-only prompt and dynamic-hook preview for settings.
// ──────────────────────────────────────────────────────────────────

/**
 * Read-only snapshot for the settings prompt viewer. Software/project are
 * static entry-file blocks; `assembled` mirrors only the dynamic hook payload.
 *
 * The `<iris-*>` wrapping in `assembled` MUST stay byte-identical to
 * FOCUS_CONTEXT_SCRIPT's output (change both together) — that script is the
 * runtime source of truth; this mirrors it for display. The focus segment is a
 * placeholder: settings has no session focus doc (the hook fills it per session).
 */
export async function assembleContextPreview(
  root: string,
): Promise<ContextPreview> {
  // Software layer — the on-disk AGENTS.md block (drift and all); falls
  // back to the factory block when not yet injected so the viewer still shows
  // the prose that WOULD be written.
  let softwareBlock: string;
  let onDisk = false;
  try {
    const agents = await fs.readFile(join(root, 'AGENTS.md'), 'utf8');
    const parsed = parseSoftwareBlock(agents);
    if (parsed) {
      softwareBlock = agents.slice(parsed.range[0], parsed.range[1]).trimEnd();
      onDisk = true;
    } else {
      softwareBlock = buildSoftwareBlock().trimEnd();
    }
  } catch {
    softwareBlock = buildSoftwareBlock().trimEnd();
  }

  let project: ContextPreview['project'] = { text: null, path: 'AGENTS.md' };
  try {
    const agents = await fs.readFile(join(root, 'AGENTS.md'), 'utf8');
    const block = parseProjectBlock(agents);
    if (block) project = { text: block.body, path: 'AGENTS.md' };
  } catch {
    // Missing standard entry is represented by a null layer.
  }
  const segments = [
    '<iris-focus path="$FOCUS_DOC">\n(Filled with the focused document for each session; settings has no session context, so this is only a placeholder.)\n</iris-focus>',
  ];

  return {
    software: { block: softwareBlock, onDisk },
    project,
    assembled: `${segments.join('\n\n')}\n`,
  };
}

async function writeEntryFileAtomic(absPath: string, text: string): Promise<void> {
  const temp = `${absPath}.tmp-${process.pid}-${randomUUID()}`;
  await fs.mkdir(dirname(absPath), { recursive: true });
  try {
    const handle = await fs.open(temp, 'wx');
    try {
      await handle.writeFile(text, 'utf8');
      await handle.sync();
    } finally {
      await handle.close();
    }
    await fs.rename(temp, absPath);
  } catch (err) {
    await fs.unlink(temp).catch(() => {});
    throw err;
  }
}

/** Reconcile both static prompt layers in one entry-file replacement. */
export async function syncPromptEntryFile(
  absPath: string,
  projectPrompt: string,
): Promise<EntrySyncResult> {
  let existed = true;
  let current = '';
  try {
    current = await fs.readFile(absPath, 'utf8');
  } catch {
    existed = false;
  }
  const software = upsertSoftwareBlock(current);
  const project = upsertProjectBlock(
    software.text,
    projectPrompt.trim() === '' ? null : projectPrompt,
  );
  const changed = software.action !== 'unchanged' || project.action !== 'unchanged';
  if (changed) {
    await writeEntryFileAtomic(absPath, project.text);
    logger.info('agent', `prompt layers synchronized in ${absPath}`);
  }
  return { existed, action: changed ? (existed ? 'updated' : 'created') : 'unchanged' };
}

/** Remove both Iris-managed blocks while preserving all foreign file content. */
export async function removePromptEntryBlocks(absPath: string): Promise<'removed' | 'unchanged'> {
  let current: string;
  try {
    current = await fs.readFile(absPath, 'utf8');
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return 'unchanged';
    throw err;
  }
  const software = removeSoftwareBlock(current);
  const project = upsertProjectBlock(software.text, null);
  if (software.action === 'unchanged' && project.action === 'unchanged') return 'unchanged';
  await writeEntryFileAtomic(absPath, project.text);
  logger.info('agent', `prompt layers removed from ${absPath}`);
  return 'removed';
}

/**
 * Write the SessionStart hook into one CLI's user-level settings file.
 * Called only after the user confirmed in the settings UI. Existing JSON is
 * merged, never replaced; an unparsable existing file aborts rather than
 * clobbering hand edits.
 */
export async function installHook(cliId: string): Promise<HookCliInfo> {
  const cli = contextHookAdapters().find((c) => c.id === cliId);
  if (!cli) throw new Error(`[agent:install-hook] unknown CLI: ${cliId}`);
  const configPath = join(cli.dir, cli.file);

  let config: Record<string, unknown> = {};
  let hadFile = false;
  try {
    const text = await fs.readFile(configPath, 'utf8');
    hadFile = true;
    config = JSON.parse(text) as Record<string, unknown>;
  } catch (err) {
    if (hadFile) {
      // Existed but didn't parse — refuse rather than clobber hand edits.
      throw new Error(
        mainT('error.hookConfigInvalid', {
          cli: cli.label,
          error: err instanceof Error ? err.message : String(err),
        }),
      );
    }
  }

  // Claude-compatible shape: hooks.<Key> = [{ hooks: [{type:'command', command}] }]
  const hooks = (config['hooks'] ??= {}) as Record<string, unknown>;
  const entries = (hooks[cli.hookKey] ??= []) as unknown[];
  if (!Array.isArray(entries)) {
    throw new Error(mainT('error.hookEntriesInvalid', { cli: cli.label, hookKey: cli.hookKey }));
  }
  const ours = eventHandlers(config, cli.hookKey).filter(isIrisHandler);
  if (
    ours.length > 0 &&
    ours.every((handler) => handler['type'] === 'command' && handler['command'] === hookCommand())
  ) {
    return { id: cli.id, label: cli.label, configPath, state: 'configured' };
  }
  let updated = false;
  for (const handler of eventHandlers(config, cli.hookKey)) {
    if (!isIrisHandler(handler)) continue;
    handler['type'] = 'command';
    handler['command'] = hookCommand();
    updated = true;
  }
  if (!updated) entries.push({ hooks: [{ type: 'command', command: hookCommand() }] });

  await fs.mkdir(cli.dir, { recursive: true });
  await fs.writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
  logger.info('agent', `SessionStart hook written: ${configPath}`);
  return { id: cli.id, label: cli.label, configPath, state: 'configured' };
}

/** Remove Iris handlers while preserving every unrelated config value. */
export function removeIrisHookHandlers(
  config: Record<string, unknown>,
  hookKey: string,
): boolean {
  const hooks = config['hooks'];
  if (!hooks || typeof hooks !== 'object' || Array.isArray(hooks)) return false;
  const hookRecord = hooks as Record<string, unknown>;
  const entries = hookRecord[hookKey];
  if (!Array.isArray(entries)) return false;

  let removed = false;
  const nextEntries = entries.flatMap((entry) => {
    if (!entry || typeof entry !== 'object' || Array.isArray(entry)) return [entry];
    const group = entry as Record<string, unknown>;
    const handlers = group['hooks'];
    if (!Array.isArray(handlers)) return [entry];
    const kept = handlers.filter((handler) => !isIrisHandler(handler));
    if (kept.length === handlers.length) return [entry];
    removed = true;
    if (kept.length === 0) return [];
    return [{ ...group, hooks: kept }];
  });

  if (!removed) return false;
  if (nextEntries.length > 0) hookRecord[hookKey] = nextEntries;
  else delete hookRecord[hookKey];
  if (Object.keys(hookRecord).length === 0) delete config['hooks'];
  return true;
}

/**
 * Remove only Iris's SessionStart handler from a user-owned CLI config.
 * Unrelated handlers and settings are preserved; the shared App-owned focus
 * script remains because other configured CLIs may still reference it.
 */
export async function removeHook(cliId: string): Promise<HookCliInfo> {
  const cli = contextHookAdapters().find((candidate) => candidate.id === cliId);
  if (!cli) throw new Error(`[agent:remove-hook] unknown CLI: ${cliId}`);
  const configPath = join(cli.dir, cli.file);

  let config: Record<string, unknown>;
  try {
    config = JSON.parse(await fs.readFile(configPath, 'utf8')) as Record<string, unknown>;
  } catch (err) {
    if (!(await exists(configPath))) {
      return { id: cli.id, label: cli.label, configPath, state: 'not-configured' };
    }
    throw new Error(
      mainT('error.hookConfigInvalid', {
        cli: cli.label,
        error: err instanceof Error ? err.message : String(err),
      }),
    );
  }

  const hooks = config['hooks'];
  const entries =
    hooks && typeof hooks === 'object' && !Array.isArray(hooks)
      ? (hooks as Record<string, unknown>)[cli.hookKey]
      : undefined;
  if (entries !== undefined && !Array.isArray(entries)) {
    throw new Error(mainT('error.hookEntriesInvalid', { cli: cli.label, hookKey: cli.hookKey }));
  }
  if (!removeIrisHookHandlers(config, cli.hookKey)) {
    return { id: cli.id, label: cli.label, configPath, state: 'not-configured' };
  }

  await fs.writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
  logger.info('agent', `SessionStart hook removed: ${configPath}`);
  return { id: cli.id, label: cli.label, configPath, state: 'not-configured' };
}
