/**
 * @file src/main/agent-injection.ts
 * @purpose The injection ADAPTER layer (misc/探讨：上下文注入和联动机制):
 *   the protocol stays "shell only sets FOCUS_DOC"; this module manages the
 *   machine-level focus-context script (~/.iris/focus-context.ps1) and the
 *   detect/suggest/write-after-confirmation flow for the agent CLIs whose
 *   SessionStart hooks can call it.
 *
 * Hook configs live in the USER'S agent config files (~/.claude/settings.json
 * etc.) — not Iris's. Writing them is therefore gated behind an explicit
 * user confirmation in the settings UI, and every write leaves a `.bak`
 * sibling. Same posture as the AGENTS.md guidance append (the single
 * sanctioned boundary exception).
 *
 * Windows-first: the script is PowerShell and the hook command invokes
 * powershell.exe. POSIX variants are a later milestone.
 */
import { promises as fs } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import type { HookCliInfo, HookCliState, InjectionState } from '@shared/types';
import { irisHomeDir } from './settings-manager';
import { logger } from './logger';

/** ~/.iris/focus-context.ps1 — always the REAL ~/.iris (hooks written into
 *  agent configs must keep working whether Iris runs as dev or packaged). */
export function focusScriptPath(): string {
  return join(irisHomeDir(), 'focus-context.ps1');
}

/**
 * The script itself: metadata block + full snapshot of the focused doc.
 * Per the approved defaults: full text by default, degrade to a pointer
 * above 32 KiB (Codex's AGENTS.md size default). Prints NOTHING when
 * FOCUS_DOC is unset — hooks fire for every session, Iris-spawned or not.
 */
export const FOCUS_CONTEXT_SCRIPT = `# Iris focus-context (machine layer, generated by Iris — editing is fine)
# SessionStart-hook payload shared by all agent CLIs: reads FOCUS_DOC (set
# by Iris when spawning a terminal) and prints a metadata block plus the
# focused doc's snapshot. Prints nothing when FOCUS_DOC is unset.
#
# This file is written with a UTF-8 BOM so Windows PowerShell 5.1 parses the
# non-ASCII text correctly (without a BOM it falls back to the system ANSI
# codepage — GBK on a Chinese Windows — and mangles every multibyte char,
# breaking the parse). The line below forces stdout to UTF-8 so the injected
# context the agent receives is not mojibake either.
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
if (-not $env:FOCUS_DOC) { exit 0 }
$root = (Get-Location).Path
$rel = $env:FOCUS_DOC
$doc = Join-Path $root $rel
Write-Output "[Iris] 本终端由 Iris 启动"
Write-Output "项目根: $root"
Write-Output "聚焦文档: $rel"
if (Test-Path (Join-Path $root '.iris/CONVENTIONS.md')) {
  Write-Output "项目宪法: .iris/CONVENTIONS.md"
}
if (Test-Path -LiteralPath $doc) {
  $size = (Get-Item -LiteralPath $doc).Length
  if ($size -le 32768) {
    Write-Output "—— 以下为聚焦文档启动时快照，写回以盘上文件为准 ——"
    Get-Content -Raw -LiteralPath $doc -Encoding UTF8
  } else {
    Write-Output ("聚焦文档超过 32 KiB（实际 " + $size + " 字节），未内联快照——请直接读取该文件。")
  }
} else {
  Write-Output "聚焦文档当前不在盘上（可能已被移动或删除）——以路径为准等待用户指示。"
}
`;

/** The one command every JSON-hook CLI gets pointed at. */
export function hookCommand(): string {
  return `powershell -NoProfile -ExecutionPolicy Bypass -File "${focusScriptPath()}"`;
}

// ──────────────────────────────────────────────────────────────────
// CLI descriptors
// ──────────────────────────────────────────────────────────────────

interface JsonHookCli {
  id: string;
  label: string;
  dir: string; // config dir under home — its presence is the install signal
  file: string; // settings file inside that dir
  /** Key inside hooks{} — Claude-compatible everywhere except Cursor's casing. */
  hookKey: string;
}

function jsonClis(): JsonHookCli[] {
  const home = homedir();
  return [
    { id: 'claude', label: 'Claude Code', dir: join(home, '.claude'), file: 'settings.json', hookKey: 'SessionStart' },
    { id: 'gemini', label: 'Gemini CLI', dir: join(home, '.gemini'), file: 'settings.json', hookKey: 'SessionStart' },
    { id: 'qwen', label: 'Qwen Code', dir: join(home, '.qwen'), file: 'settings.json', hookKey: 'SessionStart' },
    { id: 'cursor', label: 'Cursor CLI', dir: join(home, '.cursor'), file: 'cli.json', hookKey: 'sessionStart' },
  ];
}

async function exists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

/** A hooks entry counts as ours iff its command mentions the script path. */
function mentionsScript(json: unknown): boolean {
  return JSON.stringify(json ?? '').includes('focus-context.ps1');
}

export async function injectionState(): Promise<InjectionState> {
  const clis: HookCliInfo[] = [];

  for (const cli of jsonClis()) {
    const configPath = join(cli.dir, cli.file);
    if (!(await exists(cli.dir))) {
      clis.push({ id: cli.id, label: cli.label, configPath, state: 'cli-not-found' });
      continue;
    }
    let state: HookCliState = 'not-configured';
    try {
      const text = await fs.readFile(configPath, 'utf8');
      if (mentionsScript(JSON.parse(text))) state = 'configured';
    } catch {
      /* missing or unparsable settings file → treat as not configured */
    }
    clis.push({ id: cli.id, label: cli.label, configPath, state });
  }

  // Codex: hooks exist (GA 2026) but the config is TOML and project-level
  // hooks go through its own /hooks trust review — Iris detects and points,
  // never writes (write risk to a hand-maintained TOML outweighs the save).
  const codexDir = join(homedir(), '.codex');
  clis.push({
    id: 'codex',
    label: 'Codex CLI',
    configPath: join(codexDir, 'config.toml'),
    state: (await exists(codexDir)) ? 'manual-only' : 'cli-not-found',
    detail: '检测到 Codex；其 hook 配置为 TOML 且有自带信任审核（/hooks），请在 Codex 里手动把 SessionStart hook 指到上面的脚本命令。',
  });

  return {
    script: {
      path: focusScriptPath(),
      exists: await exists(focusScriptPath()),
      hookCommand: hookCommand(),
    },
    clis,
  };
}

/** Write (or refresh) the machine-level script. App-owned — overwrite OK.
 *  Written with a UTF-8 BOM (\\uFEFF): Windows PowerShell 5.1 only detects
 *  UTF-8 via the BOM, else it reads the file as the system ANSI codepage and
 *  the Chinese text / em-dashes break the parse (the SessionStart hook error
 *  reported at focus-context.ps1:17). */
const UTF8_BOM = String.fromCharCode(0xfeff); // U+FEFF — see installFocusScript

export async function installFocusScript(): Promise<{ path: string }> {
  const path = focusScriptPath();
  await fs.mkdir(irisHomeDir(), { recursive: true });
  await fs.writeFile(path, UTF8_BOM + FOCUS_CONTEXT_SCRIPT, 'utf8');
  logger.info('agent', `focus-context script written: ${path}`);
  return { path };
}

/**
 * Write the SessionStart hook into one CLI's user-level settings file.
 * Called only after the user confirmed in the settings UI. Non-destructive:
 * existing JSON is merged, never replaced; a `.bak` sibling is written
 * first; an unparsable existing file aborts (we won't clobber hand edits).
 */
export async function installHook(cliId: string): Promise<HookCliInfo> {
  const cli = jsonClis().find((c) => c.id === cliId);
  if (!cli) throw new Error(`[agent:install-hook] unknown or manual-only CLI: ${cliId}`);
  const configPath = join(cli.dir, cli.file);

  let config: Record<string, unknown> = {};
  let hadFile = false;
  try {
    const text = await fs.readFile(configPath, 'utf8');
    hadFile = true;
    config = JSON.parse(text) as Record<string, unknown>;
  } catch (err) {
    if (hadFile) {
      // Existed but didn't parse — refuse rather than clobber hand edits.
      throw new Error(
        `${cli.label} 的配置文件无法解析（${err instanceof Error ? err.message : String(err)}）——为避免破坏手工配置，请手动添加 hook。`,
      );
    }
  }

  if (mentionsScript(config)) {
    return { id: cli.id, label: cli.label, configPath, state: 'configured' };
  }

  // Claude-compatible shape: hooks.<Key> = [{ hooks: [{type:'command', command}] }]
  const hooks = (config['hooks'] ??= {}) as Record<string, unknown>;
  const entries = (hooks[cli.hookKey] ??= []) as unknown[];
  if (!Array.isArray(entries)) {
    throw new Error(`${cli.label} 配置中的 hooks.${cli.hookKey} 不是数组——请手动配置。`);
  }
  entries.push({ hooks: [{ type: 'command', command: hookCommand() }] });

  await fs.mkdir(cli.dir, { recursive: true });
  if (hadFile) {
    await fs.copyFile(configPath, `${configPath}.bak`).catch(() => {});
  }
  await fs.writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
  logger.info('agent', `SessionStart hook written: ${configPath}`);
  return { id: cli.id, label: cli.label, configPath, state: 'configured' };
}
